[tool.poetry]
name = "pretix_wrapper"
version = "0.1.0"
description = ""
authors = ["adisbladis <adisbladis@gmail.com>", "Yvan Sraka <yvan@srala.xyz>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pretix = "^4.8.0"
pretix-pages = "^1.4.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
pretix = "pretix_wrapper:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
